version: '3'
services:
  php:
    build: ./docker/php
    container_name: "php"
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql
    container_name: "mysql"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysql_db
        MYSQL_USER: admin
        MYSQL_PASSWORD: secret
        TZ: 'Asia/Tokyo'
    ports:
        - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - db_my.cnf:/etc/mysql/conf.d/my.cnf
      - db_sql:/docker-entrypoint-initdb.d

  node:
    image: node:lts-alpine3.19
    container_name: "node"
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www

  mail:
    image: mailhog/mailhog:latest
    container_name: "mailhog"
    ports:
      - 8025:8025

volumes:
  db_data:
  db_my.cnf:
  db_sql: